-- PostgreSQL dialect of database/migrations/0001_initial.sql (Sprint 03).
-- See that file for the full design reasoning -- it stays the canonical
-- commentary for this schema version. Dialect-required differences only:
--   * INTEGER PRIMARY KEY AUTOINCREMENT
--       -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--     ("BY DEFAULT", not "ALWAYS", to match SQLite's tolerance of an
--     explicitly supplied id -- nothing in this codebase supplies one,
--     but the migration should not invent a stricter contract than the
--     schema it mirrors).
-- Everything else -- tables, columns, types, constraints, indexes --
-- is identical by intent and by text.

CREATE TABLE IF NOT EXISTS vehicle (
    vin                     TEXT PRIMARY KEY,
    stock_number            TEXT,
    year                    INTEGER,
    make                    TEXT,
    model                   TEXT,
    new_or_used             TEXT,
    current_dealership_id   TEXT,
    tekion_status           TEXT,
    keyper_status           TEXT,
    mdd_status              TEXT,
    recovr_status           TEXT,
    inventory_state         TEXT
);

CREATE TABLE IF NOT EXISTS event (
    event_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin                 TEXT NOT NULL,
    event_type          TEXT NOT NULL,
    source              TEXT NOT NULL,
    sync_run_id         TEXT,
    actor_employee_id   TEXT,
    dealership_id       TEXT,
    observed_at         TEXT NOT NULL,
    summary             TEXT,
    detail_fields       TEXT,
    FOREIGN KEY (vin) REFERENCES vehicle (vin)
);

CREATE INDEX IF NOT EXISTS idx_event_vin ON event (vin);
CREATE INDEX IF NOT EXISTS idx_event_sync_run_id ON event (sync_run_id);
CREATE INDEX IF NOT EXISTS idx_event_event_type ON event (event_type);
