-- PostgreSQL dialect of database/migrations/0002_pending_identity.sql
-- (Sprint 03). See that file for the full design reasoning. Dialect
-- difference: AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE IF NOT EXISTS pending_identity (
    pending_identity_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source                TEXT NOT NULL,
    raw_identifier        TEXT NOT NULL,
    identifier_type       TEXT NOT NULL,
    status                TEXT NOT NULL DEFAULT 'pending',
    first_observed_at     TEXT NOT NULL,
    last_observed_at      TEXT NOT NULL,
    resolved_vin          TEXT,
    resolved_at           TEXT,
    UNIQUE (source, raw_identifier)
);

CREATE INDEX IF NOT EXISTS idx_pending_identity_status ON pending_identity (status);
