-- PostgreSQL dialect of database/migrations/0003_sync_run.sql
-- (Sprint 03). See that file for the full design reasoning, including
-- why event.sync_run_id deliberately has NO foreign key to this table
-- (an opaque provenance tag -- unchanged by this port; the TEXT-vs-
-- INTEGER comparison SQLite coerced silently is handled with explicit
-- CAST/str() at the few comparison/write sites instead).
-- Dialect difference: AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE IF NOT EXISTS sync_run (
    sync_run_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source              TEXT NOT NULL,
    dealership_id       TEXT,
    started_at          TEXT NOT NULL,
    completed_at        TEXT,
    records_processed   INTEGER,
    issues_found        INTEGER,
    tasks_generated     INTEGER,
    status              TEXT NOT NULL DEFAULT 'in_progress'
);

CREATE INDEX IF NOT EXISTS idx_sync_run_source ON sync_run (source);
