-- PostgreSQL dialect of database/migrations/0004_task.sql (Sprint 03).
-- See that file for the full design reasoning (commitment_standing vs
-- execution_status axes, cache-over-log, FK choices).
-- Dialect difference: AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE IF NOT EXISTS task (
    task_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin                     TEXT NOT NULL,
    dealership_id           TEXT,
    task_type               TEXT NOT NULL,
    department              TEXT,
    priority                TEXT,
    commitment_standing     TEXT NOT NULL DEFAULT 'outstanding',
    execution_status        TEXT NOT NULL DEFAULT 'not_started',
    assigned_employee_id    TEXT,
    ratified_by             TEXT,
    ratification_type       TEXT,
    escalated_from_task_id  INTEGER,
    reason                  TEXT,
    created_at              TEXT NOT NULL,
    completed_at            TEXT,
    FOREIGN KEY (vin) REFERENCES vehicle (vin),
    FOREIGN KEY (escalated_from_task_id) REFERENCES task (task_id)
);

CREATE INDEX IF NOT EXISTS idx_task_vin ON task (vin);
CREATE INDEX IF NOT EXISTS idx_task_commitment_standing ON task (commitment_standing);
CREATE INDEX IF NOT EXISTS idx_task_escalated_from_task_id ON task (escalated_from_task_id);

CREATE TABLE IF NOT EXISTS task_execution_event (
    task_execution_event_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id                  INTEGER NOT NULL,
    transition_type          TEXT NOT NULL,
    actor_employee_id        TEXT,
    note                     TEXT,
    observed_at              TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES task (task_id)
);

CREATE INDEX IF NOT EXISTS idx_task_execution_event_task_id ON task_execution_event (task_id);
