-- PostgreSQL dialect of database/migrations/0005_recommendation.sql
-- (Sprint 03). See that file for the full design reasoning.
-- Dialect difference: AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE IF NOT EXISTS recommendation (
    recommendation_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin                 TEXT NOT NULL,
    severity            TEXT,
    title               TEXT,
    detail              TEXT,
    rule_source         TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'open',
    resulting_task_id   INTEGER,
    created_at          TEXT NOT NULL,
    resolved_at         TEXT,
    FOREIGN KEY (vin) REFERENCES vehicle (vin),
    FOREIGN KEY (resulting_task_id) REFERENCES task (task_id)
);

CREATE INDEX IF NOT EXISTS idx_recommendation_vin ON recommendation (vin);
CREATE INDEX IF NOT EXISTS idx_recommendation_rule_source ON recommendation (rule_source);
CREATE INDEX IF NOT EXISTS idx_recommendation_status ON recommendation (status);
