-- PostgreSQL dialect of database/migrations/0009_access_model.sql
-- (Sprint 05). See that file for the full design reasoning -- the
-- organization/dealership-parent/user_membership model is engine-
-- independent and the reasoning stands verbatim.
--
-- Dialect differences, same conventions as 0001-0008's PG ports:
-- - AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
-- - datetime('now') -> now()::text (TEXT timestamps, matching every
--   existing table's TEXT-timestamp convention across both engines)
-- - active INTEGER 0/1 kept (not BOOLEAN) so query code compares the
--   same values on both engines
-- - ADD COLUMN IF NOT EXISTS, same idempotence convention as 0007/0008

CREATE TABLE IF NOT EXISTS organization (
    organization_id  TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    created_at       TEXT NOT NULL DEFAULT (now()::text)
);

ALTER TABLE dealership ADD COLUMN IF NOT EXISTS organization_id TEXT
    REFERENCES organization (organization_id);

CREATE TABLE IF NOT EXISTS user_membership (
    membership_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id     TEXT NOT NULL,
    organization_id  TEXT NOT NULL,
    dealership_id    TEXT NOT NULL,
    role             TEXT NOT NULL CHECK (role IN
                         ('admin', 'manager', 'lot_staff', 'sales_manager')),
    active           INTEGER NOT NULL DEFAULT 1,
    created_at       TEXT NOT NULL DEFAULT (now()::text),
    UNIQUE (auth_user_id, dealership_id),
    FOREIGN KEY (organization_id) REFERENCES organization (organization_id),
    FOREIGN KEY (dealership_id) REFERENCES dealership (dealership_id)
);

CREATE INDEX IF NOT EXISTS idx_user_membership_auth_user
    ON user_membership (auth_user_id);
