-- PostgreSQL dialect of database/migrations/0010_report_baseline.sql
-- (Sprint 10, Rail D). See that file for the full design reasoning --
-- the report_baseline concept is engine-independent and the reasoning
-- stands verbatim.
--
-- Dialect differences, same conventions as 0001-0009's PG ports:
-- - AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
-- - datetime('now') -> now()::text (TEXT timestamps, matching every
--   existing table's TEXT-timestamp convention across both engines)

CREATE TABLE IF NOT EXISTS report_baseline (
    report_baseline_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor             TEXT NOT NULL,
    report_type        TEXT NOT NULL,
    slot               TEXT NOT NULL,
    dealership_id      TEXT REFERENCES dealership (dealership_id),
    total_rows         INTEGER NOT NULL,
    valid_rows         INTEGER NOT NULL,
    sync_started_at    TEXT NOT NULL,
    recorded_at        TEXT NOT NULL DEFAULT (now()::text)
);

CREATE INDEX IF NOT EXISTS idx_report_baseline_lookup
    ON report_baseline (vendor, report_type, report_baseline_id);
